FROM koyama41/ubuntu14.04-sshd
MAINTAINER KOYAMA Youichi <koyama41@gmail.com>
WORKDIR /
RUN apt-get -y install bridge-utils
RUN apt-get -y install oping
RUN apt-get -y install dnsutils
RUN apt-get -y install bind9-host
